mkdir -p nwg/full-backup && git clone git@ci.nwgitalia.it:etl/full-backup.git nwg/full-backup
mkdir -p ticket && git clone git@ci.nwgitalia.it:nwg/ticket.git ticket
mkdir -p etl/ivd-snapshots && git clone git@ci.nwgitalia.it:etl/ivd-snapshots.git etl/ivd-snapshots
mkdir -p crm-mysql && git clone git@ci.nwgitalia.it:etl/crm-mysql.git crm-mysql
mkdir -p aws/zip && git clone git@ci.nwgitalia.it:services/zip.git aws/zip
mkdir -p vipoffice && git clone git@ci.nwgitalia.it:nwg/vipoffice.git vipoffice
mkdir -p gmd && git clone git@ci.nwgitalia.it:apis/gmd.git gmd
mkdir -p nwg/nwg-cluster-mgmt && git clone git@ci.nwgitalia.it:env/nwg-cluster-mgmt.git nwg/nwg-cluster-mgmt
mkdir -p search && git clone git@ci.nwgitalia.it:apis/search.git search
mkdir -p nwg/nwg-private-config && git clone git@ci.nwgitalia.it:package/backend/nwg-private-config.git nwg/nwg-private-config
mkdir -p nwg/nwg-model && git clone git@ci.nwgitalia.it:package/common/nwg-model.git nwg/nwg-model
mkdir -p nwg/nwg-bpl && git clone git@ci.nwgitalia.it:package/backend/nwg-bpl.git nwg/nwg-bpl
mkdir -p services/users && git clone git@ci.nwgitalia.it:services/users.git services/users
mkdir -p services/proposals && git clone git@ci.nwgitalia.it:services/proposals.git services/proposals
mkdir -p services/news && git clone git@ci.nwgitalia.it:services/news.git services/news
mkdir -p services/myfocus && git clone git@ci.nwgitalia.it:services/myfocus.git services/myfocus
mkdir -p services/leads && git clone git@ci.nwgitalia.it:services/leads.git services/leads
mkdir -p services/ivd && git clone git@ci.nwgitalia.it:services/ivd.git services/ivd
mkdir -p services/istat && git clone git@ci.nwgitalia.it:services/istat.git services/istat
mkdir -p services/influencers && git clone git@ci.nwgitalia.it:services/influencers.git services/influencers
mkdir -p services/incentives && git clone git@ci.nwgitalia.it:services/incentives.git services/incentives
mkdir -p services/hirings && git clone git@ci.nwgitalia.it:services/hirings.git services/hirings
mkdir -p services/fv && git clone git@ci.nwgitalia.it:services/fv.git services/fv
mkdir -p services/esolver && git clone git@ci.nwgitalia.it:services/esolver.git services/esolver
mkdir -p services/energy && git clone git@ci.nwgitalia.it:services/energy.git services/energy
mkdir -p services/courses && git clone git@ci.nwgitalia.it:services/courses.git services/courses
mkdir -p services/consultings && git clone git@ci.nwgitalia.it:services/consultings.git services/consultings
mkdir -p services/app_eb && git clone git@ci.nwgitalia.it:services/app_eb.git services/app_eb
mkdir -p services/anter && git clone git@ci.nwgitalia.it:services/anter.git services/anter
mkdir -p services/accounts && git clone git@ci.nwgitalia.it:services/accounts.git services/accounts
mkdir -p services/charun && git clone git@ci.nwgitalia.it:services/charun.git services/charun
mkdir -p frontends/eb && git clone git@ci.nwgitalia.it:nwg/eb.git frontends/eb
mkdir -p frontends/accounts && git clone git@ci.nwgitalia.it:nwg/accounts.git frontends/accounts
mkdir -p app/influencer-green && git clone git@ci.nwgitalia.it:nwgenergia/influencer-green.git app/influencer-green
mkdir -p aws/fv-docs-to-deloitte && git clone git@ci.nwgitalia.it:services/fv-docs-to-deloitte.git aws/fv-docs-to-deloitte
