typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#8839ef'   # mauve
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#eff1f5'   # base

typeset -g POWERLEVEL9K_DIR_BACKGROUND='#8839ef'       # mauve
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#eff1f5'       # base
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#179299'  # teal
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#df8e1d'     # yellow

typeset -g POWERLEVEL9K_TIME_FOREGROUND='#179299'      # teal
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#eff1f5'      # base

# VCS base
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#4c4f69'       # text
typeset -g POWERLEVEL9K_VCS_BACKGROUND='#eff1f5'       # base

# VCS states (pop)
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#4c4f69'       # text
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#40a02b'       # green
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#4c4f69'    # text
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#df8e1d'    # yellow
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#4c4f69'   # text
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#179299'   # teal
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='#4c4f69'  # text
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='#d20f39'  # red
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='#1e66f5'     # blue

# VCS ahead/behind + branch icon
typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_FOREGROUND='#1e66f5'   # blue
typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_FOREGROUND='#1e66f5'  # blue
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_FOREGROUND='#eff1f5'      # text
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_VISUAL_IDENTIFIER_COLOR='#eff1f5'
typeset -g POWERLEVEL9K_VCS_CLEAN_VISUAL_IDENTIFIER_COLOR='#eff1f5'
typeset -g POWERLEVEL9K_VCS_MODIFIED_VISUAL_IDENTIFIER_COLOR='#eff1f5'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_VISUAL_IDENTIFIER_COLOR='#eff1f5'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_VISUAL_IDENTIFIER_COLOR='#eff1f5'
