typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#ff79c6'   # pink
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#282a36'   # background
typeset -g POWERLEVEL9K_DIR_BACKGROUND=NONE
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#f8f8f2'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#8be9fd'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#f1fa8c'
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#8be9fd'   # cyan
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#282a36'   # background
