typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#282a36'   # pink
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#ff79c6'   # background
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND='#f8f8f2'
typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND='#ff5555'
typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='#ffb86c'
typeset -g POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND='#ff5555'
typeset -g POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_DIR_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#f8f8f2'
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#8be9fd'
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#f1fa8c'
typeset -g POWERLEVEL9K_TIME_FOREGROUND='#8be9fd'   # cyan
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#44475a'   # background

# ── Dracula: Powerlevel10k VCS (readable, fixed) ─────────────────
# bg surface #44475a | base bg #282a36 | fg #f8f8f2

# Core segment backgrounds (avoid rainbow defaults)
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND='#50fa7b'
typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND='#50fa7b'
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND='#ff5555'
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND='#ff5555'
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND='#ff5555'
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND='#44475a'

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='#ffb86c' # orange
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='#44475a'

typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND='#bd93f9'        # purple
typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND='#44475a'

typeset -g POWERLEVEL9K_DIRENV_FOREGROUND='#f1fa8c'                 # yellow
typeset -g POWERLEVEL9K_DIRENV_BACKGROUND='#44475a'

typeset -g POWERLEVEL9K_VIM_SHELL_FOREGROUND='#bd93f9'
typeset -g POWERLEVEL9K_VIM_SHELL_BACKGROUND='#44475a'

typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND='#8be9fd'    # cyan
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND='#44475a'

typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND='#50fa7b'                 # green
typeset -g POWERLEVEL9K_GCLOUD_BACKGROUND='#44475a'

typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND='#50fa7b'
typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_BACKGROUND='#44475a'

# Language/tool segments on the right prompt
typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND='#50fa7b'
typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND='#44475a'
typeset -g POWERLEVEL9K_PYENV_FOREGROUND='#f1fa8c'
typeset -g POWERLEVEL9K_PYENV_BACKGROUND='#44475a'

typeset -g POWERLEVEL9K_AMPLIFY_FOREGROUND='#ff79c6'
typeset -g POWERLEVEL9K_AMPLIFY_BACKGROUND='#44475a'

# VCS base (IMPORTANT: not terminal background)
typeset -g POWERLEVEL9K_VCS_BACKGROUND='#44475a'   # selection / surface
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#282a36'   # foreground text (dark for pop)

# Clean repo
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#282a36'

# Modified / unstaged
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#282a36'

# Untracked files
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#282a36'

# Conflicts
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='#282a36'

# Pop VCS backgrounds per state (Dracula accents)
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#50fa7b'       # green
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#f1fa8c'    # yellow
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#8be9fd'   # cyan
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='#ff5555'  # red
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='#bd93f9'     # purple

# Ahead / behind
typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_FOREGROUND='#bd93f9'   # purple
typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_FOREGROUND='#bd93f9'

# Branch icon (accent)
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_FOREGROUND='#282a36'
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_VISUAL_IDENTIFIER_COLOR='#282a36'

# Clean repo icon
typeset -g POWERLEVEL9K_VCS_CLEAN_VISUAL_IDENTIFIER_COLOR='#282a36'

# Modified files icon
typeset -g POWERLEVEL9K_VCS_MODIFIED_VISUAL_IDENTIFIER_COLOR='#282a36'

# Untracked files icon
typeset -g POWERLEVEL9K_VCS_UNTRACKED_VISUAL_IDENTIFIER_COLOR='#282a36'

# Conflicts icon
typeset -g POWERLEVEL9K_VCS_CONFLICTED_VISUAL_IDENTIFIER_COLOR='#282a36'
