typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#907aa9'   # iris
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#faf4ed'   # base

typeset -g POWERLEVEL9K_DIR_BACKGROUND='#907aa9'       # iris
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#faf4ed'       # base
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#56949f'  # foam
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#ea9d34'     # gold

typeset -g POWERLEVEL9K_TIME_FOREGROUND='#56949f'      # foam
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#faf4ed'      # base

# VCS base
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#575279'       # text
typeset -g POWERLEVEL9K_VCS_BACKGROUND='#faf4ed'       # base

# VCS states (pop)
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#575279'       # text
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#286983'       # pine
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#575279'    # text
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#ea9d34'    # gold
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#575279'   # text
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#56949f'   # foam
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='#575279'  # text
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='#b4637a'  # rose
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='#907aa9'     # iris

# VCS ahead/behind + branch icon
typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_FOREGROUND='#907aa9'   # iris
typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_FOREGROUND='#907aa9'  # iris
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_FOREGROUND='#575279'      # text
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_VISUAL_IDENTIFIER_COLOR='#575279'
typeset -g POWERLEVEL9K_VCS_CLEAN_VISUAL_IDENTIFIER_COLOR='#575279'
typeset -g POWERLEVEL9K_VCS_MODIFIED_VISUAL_IDENTIFIER_COLOR='#575279'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_VISUAL_IDENTIFIER_COLOR='#575279'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_VISUAL_IDENTIFIER_COLOR='#575279'
