typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#c4a7e7'   # iris
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#232136'   # base

typeset -g POWERLEVEL9K_DIR_BACKGROUND='#c4a7e7'       # iris
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#232136'       # base
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#9ccfd8'  # foam
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#232136'     # base (readable on iris)

typeset -g POWERLEVEL9K_TIME_FOREGROUND='#9ccfd8'      # foam
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#232136'      # base

# VCS base
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#e0def4'       # text
typeset -g POWERLEVEL9K_VCS_BACKGROUND='#232136'       # base

# VCS states (pop)
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#232136'       # base
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#3e8fb0'       # pine
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#232136'    # base
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#f6c177'    # gold
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#232136'   # base
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#9ccfd8'   # foam
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='#232136'  # base
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='#eb6f92'  # rose
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='#c4a7e7'     # iris

# VCS ahead/behind + branch icon
typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_FOREGROUND='#c4a7e7'   # iris
typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_FOREGROUND='#c4a7e7'  # iris
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_FOREGROUND='#232136'      # base
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_VISUAL_IDENTIFIER_COLOR='#232136'
typeset -g POWERLEVEL9K_VCS_CLEAN_VISUAL_IDENTIFIER_COLOR='#232136'
typeset -g POWERLEVEL9K_VCS_MODIFIED_VISUAL_IDENTIFIER_COLOR='#232136'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_VISUAL_IDENTIFIER_COLOR='#232136'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_VISUAL_IDENTIFIER_COLOR='#232136'
