typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#2e7de9'   # blue (wezterm "split")
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#e1e2e7'   # background

typeset -g POWERLEVEL9K_DIR_BACKGROUND='#2e7de9'       # blue
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#e1e2e7'       # background
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#007ea8'  # bright cyan
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#e1e2e7'     # bg (readable on blue)

typeset -g POWERLEVEL9K_TIME_FOREGROUND='#3760bf'      # foreground
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#e1e2e7'      # background

# VCS base
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#3760bf'       # fg
typeset -g POWERLEVEL9K_VCS_BACKGROUND='#e1e2e7'       # bg

# VCS states (pop)
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#3760bf'       # fg
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#587539'       # green
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#3760bf'    # fg
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#8c6c3e'    # yellow
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#3760bf'   # fg
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#007ea8'   # cyan
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='#3760bf'  # fg
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='#f52a65'  # red
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='#9854f1'     # purple

# VCS ahead/behind + branch icon
typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_FOREGROUND='#2e7de9'   # blue
typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_FOREGROUND='#2e7de9'  # blue
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_FOREGROUND='#3760bf'      # fg
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_VISUAL_IDENTIFIER_COLOR='#3760bf'
typeset -g POWERLEVEL9K_VCS_CLEAN_VISUAL_IDENTIFIER_COLOR='#3760bf'
typeset -g POWERLEVEL9K_VCS_MODIFIED_VISUAL_IDENTIFIER_COLOR='#3760bf'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_VISUAL_IDENTIFIER_COLOR='#3760bf'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_VISUAL_IDENTIFIER_COLOR='#3760bf'
