typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#7aa2f7'   # blue
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#24283b'   # bg

typeset -g POWERLEVEL9K_DIR_BACKGROUND='#7aa2f7'       # blue
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#24283b'       # bg
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#7dcfff'  # cyan
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#24283b'     # bg (readable on blue)

typeset -g POWERLEVEL9K_TIME_FOREGROUND='#c0caf5'      # fg
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#24283b'      # bg

# VCS base
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#c0caf5'       # fg
typeset -g POWERLEVEL9K_VCS_BACKGROUND='#24283b'       # bg

# VCS states (pop)
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#24283b'       # bg
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#9ece6a'       # green
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#24283b'    # bg
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#e0af68'    # yellow
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#24283b'   # bg
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#7dcfff'   # cyan
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='#24283b'  # bg
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='#f7768e'  # red
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='#bb9af7'     # purple

# VCS ahead/behind + branch icon
typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_FOREGROUND='#7aa2f7'   # blue
typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_FOREGROUND='#7aa2f7'  # blue
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_FOREGROUND='#24283b'      # bg
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_VISUAL_IDENTIFIER_COLOR='#24283b'
typeset -g POWERLEVEL9K_VCS_CLEAN_VISUAL_IDENTIFIER_COLOR='#24283b'
typeset -g POWERLEVEL9K_VCS_MODIFIED_VISUAL_IDENTIFIER_COLOR='#24283b'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_VISUAL_IDENTIFIER_COLOR='#24283b'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_VISUAL_IDENTIFIER_COLOR='#24283b'
