typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND='#82aaff'   # blue
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND='#222436'   # bg

typeset -g POWERLEVEL9K_DIR_BACKGROUND='#82aaff'       # blue
typeset -g POWERLEVEL9K_DIR_FOREGROUND='#222436'       # bg
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='#86e1fc'  # cyan
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='#222436'     # bg (readable on blue)

typeset -g POWERLEVEL9K_TIME_FOREGROUND='#c8d3f5'      # fg
typeset -g POWERLEVEL9K_TIME_BACKGROUND='#222436'      # bg

# VCS base
typeset -g POWERLEVEL9K_VCS_FOREGROUND='#c8d3f5'       # fg
typeset -g POWERLEVEL9K_VCS_BACKGROUND='#222436'       # bg

# VCS states (pop)
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND='#222436'       # bg
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND='#c3e88d'       # green
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='#222436'    # bg
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='#ffc777'    # yellow
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='#222436'   # bg
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='#86e1fc'   # cyan
typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND='#222436'  # bg
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND='#ff757f'  # red
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND='#c099ff'     # purple

# VCS ahead/behind + branch icon
typeset -g POWERLEVEL9K_VCS_COMMITS_AHEAD_FOREGROUND='#82aaff'   # blue
typeset -g POWERLEVEL9K_VCS_COMMITS_BEHIND_FOREGROUND='#82aaff'  # blue
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_FOREGROUND='#222436'      # bg
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON_VISUAL_IDENTIFIER_COLOR='#222436'
typeset -g POWERLEVEL9K_VCS_CLEAN_VISUAL_IDENTIFIER_COLOR='#222436'
typeset -g POWERLEVEL9K_VCS_MODIFIED_VISUAL_IDENTIFIER_COLOR='#222436'
typeset -g POWERLEVEL9K_VCS_UNTRACKED_VISUAL_IDENTIFIER_COLOR='#222436'
typeset -g POWERLEVEL9K_VCS_CONFLICTED_VISUAL_IDENTIFIER_COLOR='#222436'
